spring:
  application:
    name: accommodation-marketplace

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/Airbnb?createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



#this is another approch for fetching jwt key
app:
  jwt:
    key: ${JWT_SECRET}
#    key: u8F+q9ZyL1V7eR5KpT9Xw2sJ0vH3mN4Q8bYzC6dR7fU=